#!/usr/bin/php
<?php
// Nagios V-Shell
// Copyright (c) 2010-2011 Nagios Enterprises, LLC.
// Install script written by Mike Guthrie <mguthrie@nagios.com>
//

// @TODO: modify this script to find and parse the main nagios.cfg file for all 
// relevant information.

/////////////////////////////////DO NOT EDIT THIS FILE/////////////////////////
//
// Custom configuration options should be added to install-config.php

include(dirname(__FILE__).'/install-config.php');

$errors = 0;
$errorstring = '';


/////////////////////////////// Configure Apache //////////////////////////////

// Create apache conf file for project
echo "Copying apache configuration file...\n";
$output = system('/bin/cp config/vshell_apache.conf '.APACHECONF.'/vshell.conf', $code);
if($code > 0)
{
	$errorstring .= "Failed to copy apache configuration file config/vshell_apache.conf to ".APACHECONF."\n $output\n";
	$errors++;
}

// Make web directory
echo "Creating web directory...\n";
$output = system('/bin/mkdir '.TARGETDIR,$code);
if($code > 0)
{
	$errors++;
	$errorstring .= "ERROR: Failed to create ".TARGETDIR." directory \n$output\n";
}

// Copy web files to web directory
echo "Copying files...\n";
$output = system('/bin/cp -r * '.TARGETDIR.'/',$code);
if($code > 0)
{
	$errors++;
	$errorstring .= "ERROR: Failed to copy files to ".TARGETDIR." directory \n$output\n";
}

// Remove install files from target web directory
echo "Cleaning up...\n";
$output = system('/bin/rm -f '.TARGETDIR.'/install.php '.TARGETDIR.'/install-config.php',$code);
if($code > 0)
{
	$errors++;
	$errorstring .= "ERROR: Failed to delete install script from web directory \n$output\n";
}

// Restart apache service

if( file_exists('/etc/init.d/httpd') ){
	$service = '/etc/init.d/httpd';
}elseif( file_exists('/etc/init.d/apache2') ){
	$service = '/etc/init.d/apache2';
}else{
	$service = false;
}

if( ! $service)
{
	echo "Restarting apache...\n";
	$output = system($service." restart",$code);
	if($code > 0)
	{
		$errors++;
		$errorstring .= "ERROR: Failed to restart apache, please restart apache manually \n$output\n";
	}
}
else
{
	$errors++;
	$errorstring .= "ERROR: Failed to restart apache, please restart apache manually \n$output\n";
}


///////////////////////////// Check file locations ////////////////////////////

echo "Checking for file locations...\n";

// Status file

if(file_exists( '/usr/local/nagios/var/status.dat'))
{
	$statusfile = '/usr/local/nagios/var/status.dat'; //source installs
}
elseif(file_exists('/var/nagios/status.dat'))  //yum installs
{
	$statusfile = '/var/nagios/status.dat';
}
elseif(file_exists('/var/cache/nagios3/status.dat'))  //ubuntu debian nagios3 installs
{
	$statusfile = '/var/cache/nagios3/status.dat';
}
else
{
	$statusfile = '';
	$errorstring .= "NOTICE: status.dat file not found.  Please specify the location of this file in your /etc/vshell.conf file\n";
}

define('STATUSFILE', $statusfile);

// Object cache file

if(file_exists('/usr/local/nagios/var/objects.cache'))
{
	$objectfile = '/usr/local/nagios/var/objects.cache'; //source installs
}
elseif(file_exists('/var/nagios/objects.cache'))  //yum installs
{
	$objectfile = '/var/nagios/objects.cache';
}
elseif(file_exists('/var/cache/nagios3/objects.cache'))  //ubuntu debian nagios3 installs
{
	$objectfile = '/var/cache/nagios3/objects.cache';
}
else
{
	$objectfile = '';
	$errorstring .= "NOTICE: objects.cache file not found.  Please specify the location of this file in your /etc/vshell.conf file\n";
}

define('OBJECTSFILE', $objectfile);

// cgi.cfg file

if(file_exists('/usr/local/nagios/etc/cgi.cfg'))
{
	$cgifile = '/usr/local/nagios/etc/cgi.cfg';  //source installs
}
elseif(file_exists('/etc/nagios/cgi.cfg'))  //yum installs
{
	$cgifile = '/etc/nagios/cgi.cfg';
}
elseif(file_exists('/etc/nagios3/cgi.cfg'))  //ubuntu/debian nagios3 installs
{
	$cgifile = '/etc/nagios3/cgi.cfg';
}
else
{
	$cgifile = '';
	$errorstring .= "NOTICE: cgi.cfg file not found.  Please specify the location of this file in your /etc/vshell.conf file\n";
}

define('CGICFG', $cgifile);

// nagios.cmd file

if(file_exists('/usr/local/nagios/var/rw/nagios.cmd'))
{
	$nagcmd = '/usr/local/nagios/var/rw/nagios.cmd';  //source install
}
elseif(file_exists('/var/nagios/rw/nagios.cmd'))  //yum install
{
	$nagcmd = '/var/nagios/rw/nagios.cmd';
}
elseif(file_exists('/var/lib/nagios3/rw/nagios.cmd'))  //ubuntu/debian nagios3
{
	$nagcmd = '/var/lib/nagios3/rw/nagios.cmd';
}
else
{
	$nagcmd = '';
	$errorstring .= "NOTICE: nagios.cmd file not found.  Please specify the location of this file in your /etc/vshell.conf file\n";
}

define('NAGCMD', $nagcmd);


////////////////////////////// VShell conf file  //////////////////////////////

echo "Creating vshell configuration file...\n";

$output = system('/bin/touch /etc/vshell.conf', $code);
if($code > 0){
	$errors++;
	$errorstring .= "Failed to create config/vshell.conf file in /etc directory \n$output\n";
}else{
	// Try to create from template file, fall back on default file
	ob_start();
	include(dirname(__FILE__).'/config/vshell.conf.template');
	$conf = ob_get_clean();
	if( ! file_put_contents('/etc/vshell.conf', $conf) ){
		$errors++;
		$errorstring .= "Failed to create config/vshell.conf file from template.";
		$errorstring .= "Installing default file instead. Manually check /etc/vshell.conf values are correct\n";
		$output = system('/bin/cp config/vshell.conf.default /etc/vshell.conf', $code);
		if($code > 0) {
			$errors++;
			$errorstring .= "Failed to copy config/vshell.conf file to /etc directory \n$output\n";
		}
	}
}


////////////////////////////////// All done ///////////////////////////////////

echo "VShell Installation Script Complete!\n";
if( $errors > 0 ){
	echo "\n";
	echo "*** The following errors occured: \n";
	echo $errorstring."\n";
}
exit($errors);


/* End of file install.php */
