<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Nagios Config and directory locations
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/


define('VERSION', '1.9.1'); 

define('LANG','en'); 
//server root information 
define("BASEURL", 'http://localhost/vshell/');
define("SERVERBASE", 'http://localhost'); //http://<address> 
define('DIRBASE', dirname(__FILE__)); //assigns current directory as root 

//nagios core locations 
define('COREURL', 'http://localhost/nagios/'); //Nagios core web URL 
define('CORECGI', COREURL.'cgi-bin/'); //Nagios core CGI root 
define('CORECMD', CORECGI.'cmd.cgi?'); //nagios core system command cgi 

//data files for building main arrays 
# TODO: Make dynamic from /etc/vshell.conf file
define("STATUSFILE", '/var/cache/nagios3/status.dat'); //status.dat file generated by nagios 
define("OBJECTSFILE",'/var/cache/nagios3/objects.cache'); //main object configuration file generated by nagios
define("CGICFG", '/etc/nagios3/cgi.cfg'); //cfg file with permissions cfg 

define("RESULTLIMIT", 25); //limits the default number for maximum results displayed in a table 
//max time to live for apc_cached data

define('TTL',30); 











/*
|--------------------------------------------------------------------------
| File and Directory Modes
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/
define('FILE_READ_MODE', 0644);
define('FILE_WRITE_MODE', 0666);
define('DIR_READ_MODE', 0755);
define('DIR_WRITE_MODE', 0777);

/*
|--------------------------------------------------------------------------
| File Stream Modes
|--------------------------------------------------------------------------
|
| These modes are used when working with fopen()/popen()
|
*/

define('FOPEN_READ',							'rb');
define('FOPEN_READ_WRITE',						'r+b');
define('FOPEN_WRITE_CREATE_DESTRUCTIVE',		'wb'); // truncates existing file data, use with care
define('FOPEN_READ_WRITE_CREATE_DESTRUCTIVE',	'w+b'); // truncates existing file data, use with care
define('FOPEN_WRITE_CREATE',					'ab');
define('FOPEN_READ_WRITE_CREATE',				'a+b');
define('FOPEN_WRITE_CREATE_STRICT',				'xb');
define('FOPEN_READ_WRITE_CREATE_STRICT',		'x+b');






/* End of file constants.php */
/* Location: ./application/config/constants.php */
